-- V1 - baseline do schema que ja existia antes do Flyway.
--
-- Gerado com pg_dump --schema-only do banco de desenvolvimento em 2026-08-16 e
-- limpo a mao: sairam os meta-comandos do psql (restrict/unrestrict, que so o
-- cliente psql entende e o Flyway nao executa) e o preambulo de SET, que
-- pertence ao dump e nao ao schema.
--
-- ESTE ARQUIVO NAO RODA NO BANCO QUE JA EXISTE. Com baseline-on-migrate o
-- Flyway apenas carimba o banco atual como "ja esta no V1" e segue para o V2.
-- Ele roda de verdade so onde o schema nao existe: banco novo e o Postgres
-- efemero dos testes. E isso que torna o teste uma prova - o mesmo arquivo que
-- descreve producao e o que monta o banco de teste.
--
-- Inclui o que antes era criado na mao no startup (PgTrgmConfig e
-- IndicesRecorrenciaConfig): a extensao pg_trgm e os dois indices de
-- unicidade de recorrencia.

--
--

--
-- Name: pg_trgm; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;

--
-- Name: EXTENSION pg_trgm; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION pg_trgm IS 'text similarity measurement and index searching based on trigrams';

--
-- Name: aporte; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.aporte (
    id bigint NOT NULL,
    data date,
    valor numeric(38,2),
    objetivo_id bigint NOT NULL
);

--
-- Name: aporte_cdb; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.aporte_cdb (
    id bigint NOT NULL,
    data_aplicacao date,
    valor_aplicado numeric(38,2),
    investimento_cdb_id bigint NOT NULL
);

--
-- Name: aporte_cdb_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.aporte_cdb ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.aporte_cdb_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: aporte_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.aporte ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.aporte_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: categoria; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.categoria (
    id bigint NOT NULL,
    nome character varying(255),
    tipo character varying(255) NOT NULL,
    usuario_id bigint NOT NULL,
    data_criacao timestamp(6) without time zone,
    CONSTRAINT categoria_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['FIXA'::character varying, 'VARIAVEL'::character varying])::text[])))
);

--
-- Name: categoria_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.categoria ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categoria_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: cdi_diario; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cdi_diario (
    data date NOT NULL,
    taxa_percentual numeric(9,6)
);

--
-- Name: despesa; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.despesa (
    id bigint NOT NULL,
    data date,
    descricao character varying(255),
    valor numeric(38,2),
    categoria_id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    recorrencia_id bigint,
    mes_referencia date
);

--
-- Name: despesa_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.despesa ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.despesa_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: investimento_cdb; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.investimento_cdb (
    id bigint NOT NULL,
    data_resgate date,
    descricao character varying(255),
    percentual_cdi numeric(38,2),
    usuario_id bigint NOT NULL
);

--
-- Name: investimento_cdb_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.investimento_cdb ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.investimento_cdb_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: limite_categoria; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.limite_categoria (
    id bigint NOT NULL,
    valor_limite numeric(38,2),
    categoria_id bigint NOT NULL,
    usuario_id bigint NOT NULL
);

--
-- Name: limite_categoria_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.limite_categoria ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.limite_categoria_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: objetivo; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.objetivo (
    id bigint NOT NULL,
    data_alvo date,
    descricao character varying(255),
    incentivo character varying(255),
    valor_alvo numeric(38,2),
    valor_atual numeric(38,2),
    investimento_cdb_id bigint,
    usuario_id bigint NOT NULL
);

--
-- Name: objetivo_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.objetivo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.objetivo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: recorrencia_despesa; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recorrencia_despesa (
    id bigint NOT NULL,
    ativa boolean NOT NULL,
    data_inicio date,
    dia_do_mes integer NOT NULL,
    categoria_id bigint NOT NULL,
    usuario_id bigint NOT NULL
);

--
-- Name: recorrencia_despesa_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.recorrencia_despesa ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recorrencia_despesa_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: recorrencia_renda; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recorrencia_renda (
    id bigint NOT NULL,
    ativa boolean NOT NULL,
    data_inicio date,
    usuario_id bigint NOT NULL
);

--
-- Name: recorrencia_renda_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.recorrencia_renda ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recorrencia_renda_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: renda; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.renda (
    id bigint NOT NULL,
    descricao character varying(255),
    mes_referencia date,
    tipo character varying(255),
    valor numeric(38,2),
    usuario_id bigint NOT NULL,
    recorrencia_id bigint,
    CONSTRAINT renda_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['FIXA'::character varying, 'FREELA'::character varying, 'RETORNO_INVESTIMENTOS'::character varying])::text[])))
);

--
-- Name: renda_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.renda ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.renda_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: usuario; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuario (
    id bigint NOT NULL,
    data_criacao timestamp(6) without time zone,
    email character varying(255),
    nome character varying(255),
    senha character varying(255),
    foto bytea,
    foto_tipo character varying(255),
    termos_aceitos_em timestamp(6) without time zone
);

--
-- Name: usuario_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.usuario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: aporte_cdb aporte_cdb_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.aporte_cdb
    ADD CONSTRAINT aporte_cdb_pkey PRIMARY KEY (id);

--
-- Name: aporte aporte_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.aporte
    ADD CONSTRAINT aporte_pkey PRIMARY KEY (id);

--
-- Name: categoria categoria_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categoria
    ADD CONSTRAINT categoria_pkey PRIMARY KEY (id);

--
-- Name: cdi_diario cdi_diario_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cdi_diario
    ADD CONSTRAINT cdi_diario_pkey PRIMARY KEY (data);

--
-- Name: despesa despesa_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.despesa
    ADD CONSTRAINT despesa_pkey PRIMARY KEY (id);

--
-- Name: investimento_cdb investimento_cdb_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.investimento_cdb
    ADD CONSTRAINT investimento_cdb_pkey PRIMARY KEY (id);

--
-- Name: limite_categoria limite_categoria_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.limite_categoria
    ADD CONSTRAINT limite_categoria_pkey PRIMARY KEY (id);

--
-- Name: objetivo objetivo_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.objetivo
    ADD CONSTRAINT objetivo_pkey PRIMARY KEY (id);

--
-- Name: recorrencia_despesa recorrencia_despesa_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recorrencia_despesa
    ADD CONSTRAINT recorrencia_despesa_pkey PRIMARY KEY (id);

--
-- Name: recorrencia_renda recorrencia_renda_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recorrencia_renda
    ADD CONSTRAINT recorrencia_renda_pkey PRIMARY KEY (id);

--
-- Name: renda renda_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.renda
    ADD CONSTRAINT renda_pkey PRIMARY KEY (id);

--
-- Name: renda uk_renda_recorrencia_mes; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.renda
    ADD CONSTRAINT uk_renda_recorrencia_mes UNIQUE (recorrencia_id, mes_referencia);

--
-- Name: objetivo uklq4ffd3yttg7dmk6lguh0ffxp; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.objetivo
    ADD CONSTRAINT uklq4ffd3yttg7dmk6lguh0ffxp UNIQUE (investimento_cdb_id);

--
-- Name: usuario usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY (id);

--
-- Name: uk_despesa_recorrencia_mes; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uk_despesa_recorrencia_mes ON public.despesa USING btree (recorrencia_id, date_trunc('month'::text, (data)::timestamp without time zone));

--
-- Name: aporte_cdb fk1jjhaenpmiytix5i127yx1r97; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.aporte_cdb
    ADD CONSTRAINT fk1jjhaenpmiytix5i127yx1r97 FOREIGN KEY (investimento_cdb_id) REFERENCES public.investimento_cdb(id);

--
-- Name: categoria fk6byc7k2m35w3fwmcba5f0rqtf; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categoria
    ADD CONSTRAINT fk6byc7k2m35w3fwmcba5f0rqtf FOREIGN KEY (usuario_id) REFERENCES public.usuario(id);

--
-- Name: recorrencia_despesa fk8afp6syystqwhmcxnh8cjhrke; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recorrencia_despesa
    ADD CONSTRAINT fk8afp6syystqwhmcxnh8cjhrke FOREIGN KEY (usuario_id) REFERENCES public.usuario(id);

--
-- Name: objetivo fk8tgg8arf1nu6mtytgymba2leh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.objetivo
    ADD CONSTRAINT fk8tgg8arf1nu6mtytgymba2leh FOREIGN KEY (usuario_id) REFERENCES public.usuario(id);

--
-- Name: aporte fk8vi54ag6clku66eyti6gmsrrx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.aporte
    ADD CONSTRAINT fk8vi54ag6clku66eyti6gmsrrx FOREIGN KEY (objetivo_id) REFERENCES public.objetivo(id);

--
-- Name: recorrencia_renda fka08hiskjqe0scaj80gux1p9cj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recorrencia_renda
    ADD CONSTRAINT fka08hiskjqe0scaj80gux1p9cj FOREIGN KEY (usuario_id) REFERENCES public.usuario(id);

--
-- Name: recorrencia_despesa fkcaoj1q4low4bbbqdbgnay6rsi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recorrencia_despesa
    ADD CONSTRAINT fkcaoj1q4low4bbbqdbgnay6rsi FOREIGN KEY (categoria_id) REFERENCES public.categoria(id);

--
-- Name: renda fkgjsd1kpbhxy714yt0pbf6txo4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.renda
    ADD CONSTRAINT fkgjsd1kpbhxy714yt0pbf6txo4 FOREIGN KEY (recorrencia_id) REFERENCES public.recorrencia_renda(id);

--
-- Name: despesa fkgx7q6554dv8998l6u55l3bb5x; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.despesa
    ADD CONSTRAINT fkgx7q6554dv8998l6u55l3bb5x FOREIGN KEY (recorrencia_id) REFERENCES public.recorrencia_despesa(id);

--
-- Name: despesa fkhhqg5jva3eym0n1hp2gedxsq1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.despesa
    ADD CONSTRAINT fkhhqg5jva3eym0n1hp2gedxsq1 FOREIGN KEY (categoria_id) REFERENCES public.categoria(id);

--
-- Name: limite_categoria fkmonh86va91f5pc2ja2lekbe7e; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.limite_categoria
    ADD CONSTRAINT fkmonh86va91f5pc2ja2lekbe7e FOREIGN KEY (usuario_id) REFERENCES public.usuario(id);

--
-- Name: objetivo fko2mw6a6ue793t8ghc8lokm3fe; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.objetivo
    ADD CONSTRAINT fko2mw6a6ue793t8ghc8lokm3fe FOREIGN KEY (investimento_cdb_id) REFERENCES public.investimento_cdb(id);

--
-- Name: despesa fkpd22ej1eellqho1wi3gt6noha; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.despesa
    ADD CONSTRAINT fkpd22ej1eellqho1wi3gt6noha FOREIGN KEY (usuario_id) REFERENCES public.usuario(id);

--
-- Name: limite_categoria fkqq9md5m8yquri5hiep7i25kgi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.limite_categoria
    ADD CONSTRAINT fkqq9md5m8yquri5hiep7i25kgi FOREIGN KEY (categoria_id) REFERENCES public.categoria(id);

--
-- Name: renda fkr5q0hgb1rgm91x5t0lg4js8tj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.renda
    ADD CONSTRAINT fkr5q0hgb1rgm91x5t0lg4js8tj FOREIGN KEY (usuario_id) REFERENCES public.usuario(id);

--
-- Name: investimento_cdb fkt0b9gog5w7ue1fgqudhgiwi73; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.investimento_cdb
    ADD CONSTRAINT fkt0b9gog5w7ue1fgqudhgiwi73 FOREIGN KEY (usuario_id) REFERENCES public.usuario(id);

--
--
